name: Build AlphaPlot for macOS (ARM)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew update
        brew install qt5 cmake
        brew link qt5 --force

    - name: Configure Build
      run: cmake -S . -B build -DCMAKE_PREFIX_PATH=$(brew --prefix qt5)

    - name: Build
      run: cmake --build build --config Release

    - name: Package
      run: cd build && make package
