name: macOS M1 Build

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: macos-12
    name: Build on macOS M1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew update
        brew install cmake
        brew install qt
        brew install gsl

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_PREFIX_PATH=$(brew --prefix qt) ..

    - name: Build
      run: |
        cd build
        make -j$(sysctl -n hw.ncpu)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
