name: MacOS arm Build

on:
  workflow_dispatch: # 手动触发

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: clone repository
      uses: actions/checkout@v2
        
    - name: Install Dependantcies And Make Mac
      run: |
        brew install qtcore qtgui qtwidgets qtopengl qtnetwork qtsvg qtscript qtscripttools qtprintsupport qtdatavis3d
        brew install gsl
        qmake CONFIG+=osx_dist
        make
 
