name: MacOS arm Build

on:
  workflow_dispatch: # 手动触发

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: clone repository
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcore qtgui qtwidgets qtopengl qtnetwork qtsvg qtscript qtscripttools qtprintsupport qtdatavis3d'
            
    - name: Install Dependantcies And Make Mac
      run: |
        brew install gsl
        qmake CONFIG+=osx_dist
        make
 
